
STEPS = 24
EFF_TRANSMISSION = .98
EFF_DISTRIBUTION = .96
EFF_STEP_UP = .99
EFF_STEP_DOWN = .99
STEPS = 24 #24 hours
AVRG_CONSUMPTION_PER_HOUSE_PER_PERSON = 2000
TWO_PERSON_HOUSEHOLD = AVRG_CONSUMPTION_PER_HOUSE_PER_PERSON + (1300 * 1)
TWO_PERSON_HOUSEHOLD = AVRG_CONSUMPTION_PER_HOUSE_PER_PERSON + (1300 * 2)
