STEPS = 24 #24 hours
AVRG_CONSUMPTION_PER_HOUSE_PER_PERSON = 2000
TWO_PERSON_HOUSEHOLD = AVRG_CONSUMPTION_PER_HOUSE_PER_PERSON + (1300 * 1)
TWO_PERSON_HOUSEHOLD = AVRG_CONSUMPTION_PER_HOUSE_PER_PERSON + (1300 * 2)

WINDOW = [1]*STEPS